name: dorecipes
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  http: ^0.13.1
  flutter_html: ^1.3.0
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  permission_handler: ^6.1.1
  fluttertoast: ^8.0.3
  data_connection_checker: ^0.3.4
  salomon_bottom_bar: ^3.0.0
  font_awesome_flutter: ^9.0.0
  cached_network_image: ^3.0.0


flutter_native_splash:
  image: assets/images/splash_icon.png

  color: "#000000"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: BalooTamma2
      fonts:
        - asset: fonts/BalooTamma2-Medium.ttf